apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: friend-service
  name: friend-service
spec:
  ports:
  - name: "main"
    port: 80
    targetPort: 8081
  selector:
    app: friend-service
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: friend-service
  name: friend-service
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: friend-service
  template:
    metadata:
      labels:
        app: friend-service
    spec:
      containers:
      - env:
        - name: DATABASE_HOST
          value: den1.mysql6.gear.host
        - name: DATABASE_NAME
          value: coolfriends          
        - name: DATABASE_PASSWORD
          value: Ab77F-88M_9l
        - name: DATABASE_PORT
          value: "3306"
        - name: DATABASE_USER
          value: coolfriends
        image: eugeneywang/friendservice:latest
        name: friendservice
        ports:
        - containerPort: 8081
        resources:
          requests:
            cpu: 400m
      restartPolicy: Always
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  DATABASE_NAME: Y29vbGZyaWVuZHMK
  DATABASE_USER: Y29vbGZyaWVuZHMK
  DATABASE_PASSWORD: QWI3N0YtODhNXzlsCg==
