apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: friend-service
  name: friend-service
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    app: friend-service
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: friend-service
  name: friend-service
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: friend-service
  template:
    metadata:
      labels:
        app: friend-service
    spec:
      containers:
      - env:
        - name: DATABASE_HOST
          value: "sql9.freemysqlhosting.net"

        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DATABASE_NAME

        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DATABASE_PASSWORD

        - name: DATABASE_PORT
          value: "3306"

        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DATABASE_USER

        image: friend-service:v0
        name: friendservice
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  DATABASE_NAME: c3FsOTI2MjM3Nw==
  DATABASE_USER: c3FsOTI2MjM3Nw==
  DATABASE_PASSWORD: V1FVSDg0dHNERA==
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: mysql-external
spec:
  hosts:
  - sql9.freemysqlhosting.net
  addresses:
  - sql9.freemysqlhosting.net
  ports:
  - name: tcp
    number: 3306
    protocol: tcp
  location: MESH_EXTERNAL
