spring:
  application:
    name: bff

url:
  accountURL: http://localhost:8082
  friendURL: http://localhost:8081
server:
  port: 8080
management:
  security:
    enabled: false
---
spring:
  profiles: container
  url:
    accountURL: ${account}
    friendURL: ${friend}
